document.addEventListener("DOMContentLoaded",()=>{
  const problems=["Perselisihan antarwarga","Utang-piutang","Perjanjian","Pertanahan","Waris","Keluarga","Perkawinan","Ketenagakerjaan","Perlindungan konsumen","Administrasi kependudukan","Perlindungan perempuan & anak","Dugaan tindak pidana","Perselisihan usaha","Lain-lain"];
  const efforts=["Belum pernah","Musyawarah keluarga","Mediasi RT/RW","Mediasi Pemerintah Desa","Pengaduan ke instansi lain","Pengaduan ke Kepolisian","Upaya hukum lainnya"];
  const documents=["KTP","KK","Surat perjanjian","Surat tanah/sertifikat","Kwitansi","Bukti transfer","Foto","Percakapan/pesan elektronik","Surat dari instansi","Dokumen lainnya"];
  const makeChecks=(id,name,items)=>{document.getElementById(id).innerHTML=items.map(v=>`<label><input type="checkbox" name="${name}" value="${v}"><span>${v}</span></label>`).join("")};
  makeChecks("problemChecks","jenis_permasalahan",problems);makeChecks("effortChecks","upaya_dilakukan",efforts);makeChecks("documentChecks","jenis_dokumen",documents);
  document.getElementById("serviceTypes").innerHTML=problems.map(v=>`<span>${v}</span>`).join("");
  const menu=document.getElementById("mobileMenu"),menuBtn=document.getElementById("menuBtn");menuBtn.addEventListener("click",()=>{const open=menu.classList.toggle("open");menuBtn.setAttribute("aria-expanded",String(open));menuBtn.textContent=open?"close":"menu"});
  const formSection=document.getElementById("formSection");const openForm=()=>{const session=window.AuthSession?.get();if(!session){window.AuthSession?.requireLogin("/posbankum#formulir");return}const form=document.getElementById("posbankumForm");if(!form.elements.nama_lengkap.value)form.elements.nama_lengkap.value=session.nama||"";if(!form.elements.nik.value)form.elements.nik.value=session.nik||"";formSection.classList.remove("hidden");formSection.scrollIntoView({behavior:"smooth"})};document.querySelectorAll("[data-open-form]").forEach(b=>b.addEventListener("click",openForm));document.getElementById("closeForm").addEventListener("click",()=>{formSection.classList.add("hidden")});if(location.hash==="#formulir"&&window.AuthSession?.isAuthenticated())openForm();
  document.getElementById("problemChecks").addEventListener("change",()=>{const other=document.querySelector('input[name="jenis_permasalahan"][value="Lain-lain"]');document.getElementById("otherProblemWrap").classList.toggle("hidden",!other.checked)});
  const fileInput=document.querySelector('input[name="documents"]');fileInput.addEventListener("change",()=>{const files=[...fileInput.files];const invalid=files.length>10||files.some(f=>f.size>5*1024*1024);document.getElementById("fileList").innerHTML=files.map(f=>`<li>${f.name} (${(f.size/1024/1024).toFixed(2)} MB)</li>`).join("");if(invalid){fileInput.value="";show("Maksimal 10 file dan setiap file tidak boleh melebihi 5 MB.",true)}});
  const show=(text,error=false)=>{const el=document.getElementById("formMessage");el.textContent=text;el.className=`form-message show ${error?"error":"success"}`};
  document.getElementById("posbankumForm").addEventListener("submit",async e=>{e.preventDefault();const session=window.AuthSession?.get();if(!session){window.AuthSession?.requireLogin("/posbankum#formulir");return}const form=e.currentTarget,button=document.getElementById("submitButton");const data=new FormData(form);["jenis_permasalahan","upaya_dilakukan","jenis_dokumen"].forEach(name=>{const values=data.getAll(name);data.delete(name);data.append(name,JSON.stringify(values))});button.disabled=true;button.textContent="Mengirim...";try{const response=await fetch(`${window.API_BASE_URL}/posbankum`,{method:"POST",headers:{Authorization:`Bearer ${session.token}`},body:data});const result=await response.json();if(response.status===401){window.AuthSession.requireLogin("/posbankum#formulir");return}if(!response.ok)throw new Error(result.message||"Pengaduan gagal dikirim.");show(`Pengaduan berhasil. Nomor Register: ${result.data.nomor_register}`);form.reset();document.getElementById("fileList").innerHTML="";document.getElementById("otherProblemWrap").classList.add("hidden");}catch(error){show(error.message,true)}finally{button.disabled=false;button.textContent="Kirim Pengaduan"}});
});
