document.addEventListener("DOMContentLoaded",()=>{
  const token=()=>localStorage.getItem("token")||"";
  const esc=(v="")=>{const d=document.createElement("div");d.textContent=String(v??"");return d.innerHTML};
  const categories=["Dapat diupayakan musyawarah/mediasi desa","Memerlukan konsultasi hukum lebih lanjut","Memerlukan rujukan ke FH UMAHA/LBH Maarif","Memerlukan rujukan ke instansi/lembaga berwenang","Memerlukan tindakan segera (potensi keselamatan/tindak pidana)","Lain-lain"];
  const followups=["Konsultasi awal","Musyawarah","Mediasi para pihak","Penjadwalan pertemuan","Koordinasi dengan Pemerintah Desa","Koordinasi dengan FH UMAHA/LBH Maarif","Rujukan ke instansi lain","Perkara selesai","Masih dalam proses"];
  const finals=["Selesai melalui musyawarah","Selesai melalui mediasi","Dirujuk ke FH UMAHA/LBH Maarif","Dirujuk ke instansi berwenang","Masih dalam proses","Tidak dapat dilanjutkan"];
  const checks=(id,name,items,type="checkbox")=>{document.getElementById(id).innerHTML=items.map(v=>`<label><input type="${type}" name="${name}" value="${esc(v)}"><span>${esc(v)}</span></label>`).join("")};checks("categoryChecks","kategori_identifikasi",categories);checks("followupChecks","tindak_lanjut",followups);checks("finalStatusRadios","status_akhir",finals,"radio");
  let rows=[];const tbody=document.getElementById("complaintRows"),filter=document.getElementById("statusFilter"),search=document.getElementById("searchInput"),modal=document.getElementById("detailModal"),form=document.getElementById("handlingForm");
  const badge=status=>`<span class="status-badge ${status==="Menunggu"?"status-Menunggu":status==="Selesai"?"status-Selesai":"status-default"}">${esc(status)}</span>`;
  function render(){const q=search.value.toLowerCase();const visible=rows.filter(x=>(!filter.value||x.status===filter.value)&&(`${x.nomor_register} ${x.nama_lengkap} ${(x.jenis_permasalahan||[]).join(" ")}`).toLowerCase().includes(q));tbody.innerHTML=visible.length?visible.map(x=>`<tr><td class="font-semibold">${esc(x.nomor_register)}</td><td>${esc(x.nama_lengkap)}</td><td>${new Date(x.tanggal_pengaduan).toLocaleDateString("id-ID")}</td><td>${esc((x.jenis_permasalahan||[]).join(", "))}</td><td>${badge(x.status)}</td><td><button class="detail-button" data-id="${esc(x.id)}">Lihat detail</button></td></tr>`).join(""):'<tr><td colspan="6" class="py-10 text-center text-gray-500">Tidak ada pengaduan yang sesuai.</td></tr>';document.getElementById("tableInfo").textContent=`${visible.length} pengaduan ditampilkan`;}
  async function load(){tbody.innerHTML='<tr><td colspan="6" class="py-10 text-center text-gray-500">Memuat data rahasia...</td></tr>';try{const response=await fetch(`${window.API_BASE_URL}/posbankum/admin`,{headers:{Authorization:`Bearer ${token()}`}});const result=await response.json();if(!response.ok)throw new Error(result.message);rows=result.data||[];render()}catch(error){tbody.innerHTML=`<tr><td colspan="6" class="py-10 text-center text-red-600">${esc(error.message||"Data gagal dimuat.")}</td></tr>`}}filter.addEventListener("change",render);search.addEventListener("input",render);
  const val=(label,value)=>`<div class="detail-item"><span>${esc(label)}</span><p>${esc(value||"-")}</p></div>`;
  async function openDetail(id){try{const response=await fetch(`${window.API_BASE_URL}/posbankum/admin/${encodeURIComponent(id)}`,{headers:{Authorization:`Bearer ${token()}`}});const result=await response.json();if(!response.ok)throw new Error(result.message);const x=result.data,p=x.pihak_terkait||{};document.getElementById("complaintDetail").innerHTML=`<section class="detail-section"><h3>${esc(x.nomor_register)}</h3><div class="detail-grid">${val("Nama Pengadu",x.nama_lengkap)}${val("NIK",x.nik)}${val("Tempat/Tanggal Lahir",`${x.tempat_lahir}, ${x.tanggal_lahir}`)}${val("Jenis Kelamin",x.jenis_kelamin)}${val("No. HP/WhatsApp",x.no_hp)}${val("Pekerjaan",x.pekerjaan)}${val("Status dalam permasalahan",x.status_dalam_permasalahan)}${val("Alamat",x.alamat)}</div></section><section class="detail-section"><h3>Pihak Terkait</h3><div class="detail-grid">${val("Nama",p.nama)}${val("No. HP",p.no_hp)}${val("Hubungan",p.hubungan)}${val("Alamat",p.alamat)}</div></section><section class="detail-section"><h3>Permasalahan dan Upaya</h3><div class="detail-grid">${val("Jenis",(x.jenis_permasalahan||[]).join(", "))}${val("Waktu",x.waktu_kejadian)}${val("Tempat",x.tempat_kejadian)}${val("Upaya",(x.upaya_dilakukan||[]).join(", "))}${val("Hasil upaya",x.hasil_upaya)}${val("Harapan",x.harapan_pengadu)}</div><div class="detail-item mt-4"><span>Uraian</span><p>${esc(x.uraian)}</p></div></section><section class="detail-section documents"><h3>Dokumen/Bukti</h3>${(x.dokumen||[]).length?(x.dokumen||[]).map(d=>d.url?`<a href="${esc(d.url)}" target="_blank" rel="noopener noreferrer">${esc(d.name)}</a>`:`<p>${esc(d.name)} (tautan tidak tersedia)</p>`).join(""):"<p>Tidak ada dokumen.</p>"}</section>`;
      form.elements.id.value=x.id;form.elements.status.value=x.status;form.elements.catatan_petugas.value=x.catatan_petugas||"";form.elements.kategori_lainnya.value=x.kategori_lainnya||"";form.elements.tanggal_tindak_lanjut.value=x.tanggal_tindak_lanjut||"";form.elements.petugas_penanggung_jawab.value=x.petugas_penanggung_jawab||"";form.elements.hasil_penanganan.value=x.hasil_penanganan||"";document.querySelectorAll('#handlingForm input[type="checkbox"],#handlingForm input[type="radio"]').forEach(el=>{const values=el.name==="kategori_identifikasi"?x.kategori_identifikasi||[]:el.name==="tindak_lanjut"?x.tindak_lanjut||[]:[x.status_akhir];el.checked=values.includes(el.value)});document.getElementById("otherCategory").classList.toggle("hidden",!(x.kategori_identifikasi||[]).includes("Lain-lain"));modal.classList.remove("hidden");document.body.style.overflow="hidden";}catch(error){Swal.fire("Gagal",error.message,"error")}}
  tbody.addEventListener("click",e=>{const b=e.target.closest("[data-id]");if(b)openDetail(b.dataset.id)});document.getElementById("categoryChecks").addEventListener("change",()=>document.getElementById("otherCategory").classList.toggle("hidden",!document.querySelector('input[name="kategori_identifikasi"][value="Lain-lain"]').checked));document.querySelectorAll("[data-close-modal]").forEach(b=>b.addEventListener("click",()=>{modal.classList.add("hidden");document.body.style.overflow=""}));
  form.addEventListener("submit",async e=>{e.preventDefault();const data=new FormData(form),body={};["kategori_identifikasi","tindak_lanjut"].forEach(n=>body[n]=data.getAll(n));["status","status_akhir","kategori_lainnya","catatan_petugas","tanggal_tindak_lanjut","petugas_penanggung_jawab","hasil_penanganan"].forEach(n=>body[n]=data.get(n)||null);try{const response=await fetch(`${window.API_BASE_URL}/posbankum/admin/${encodeURIComponent(data.get("id"))}`,{method:"PUT",headers:{Authorization:`Bearer ${token()}`,"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw new Error(result.message);await Swal.fire("Berhasil",result.message,"success");modal.classList.add("hidden");document.body.style.overflow="";load()}catch(error){Swal.fire("Gagal",error.message,"error")}});load();
});
